# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine AS builder

# Install dependencies
RUN apk add --no-cache python3 make g++ \
    && npm install -g pnpm

WORKDIR /app

# Copy project files
COPY package.json pnpm-lock.yaml tsconfig.json ./
COPY src ./src

# Install and build
RUN pnpm install --frozen-lockfile
RUN pnpm run build

# Production image
FROM node:lts-alpine AS runner
WORKDIR /app

# Copy build artifacts and package metadata
COPY --from=builder /app/dist ./dist
COPY package.json ./

# Install production dependencies
RUN npm install --production --ignore-scripts --no-lockfile

ENV NODE_ENV=production

CMD ["node", "dist/cli.js"]
